### ISSUE TITLE
Compilation is broken

### ISSUE THREAD

**Issue by danielporto** [fastogt/fastotvlite_mobile#1]
Hello! 
Thanks for this nice project!
I tried to build (the last commit c47dcfab68203db32f922f224f536069d2fe655d ) but compilation is failing. Perhaps some updated files were not pushed to the repo?

Compiler message:
lib/tv/streams/tv_live_edit_channel.dart:24:65: Error: The method 'group' isn't defined for the class 'LiveStream'.
 - 'LiveStream' is from 'package:fastotvlite/channels/live_stream.dart' ('lib/channels/live_stream.dart').
Try correcting the name to the name of an existing method, or defining a method named 'group'.
    groupController = TextEditingController(text: widget.stream.group());
                                                                ^^^^^
lib/tv/streams/tv_live_edit_channel.dart:71:45: Error: The argument type 'String' can't be assigned to the parameter type 'List<String>'.
 - 'List' is from 'dart:core'.
    widget.stream.setGroups(groupController.text);
                                            ^
lib/tv/vods/tv_vod_edit_channel.dart:22:51: Error: The argument type 'List<String>' can't be assigned to the parameter type 'String'.
 - 'List' is from 'dart:core'.
    groupController = TextEditingController(text: groups);
                                                  ^
lib/tv/vods/tv_vod_edit_channel.dart:69:45: Error: The argument type 'String' can't be assigned to the parameter type 'List<String>'.
 - 'List' is from 'dart:core'.
    widget.stream.setGroups(groupController.text);
                                            ^
lib/mobile/add_streams/edit_channel_page.dart:23:51: Error: The argument type 'List<String>' can't be assigned to the parameter type 'String'.
 - 'List' is from 'dart:core'.
    groupController = TextEditingController(text: groups);
                                                  ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script '/usr/local/Caskroom/flutter/latest/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 882

**Comment by topilski** [comment]
Morning @danielporto , thank you for the issue we will fix asap!

**Comment by danielporto** [comment]
Btw, here follows details about the environment where I tried to build it.

[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.14.6 18G4032, locale en-PT)
    • Flutter version 1.17.0 at /usr/local/Caskroom/flutter/latest/flutter
    • Framework revision e6b34c2b5c (9 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Platform android-29, build-tools 29.0.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.1
[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

Thanks again for this very nice app.

**Comment by topilski** [comment]
Morning @danielporto, please check

**Comment by danielporto** [comment]
Nice, it did compile and open on android studio.
it did not work on the iphone emulator though. 
thanks

**Comment by topilski** [comment]
so we can close this issue?

**Comment by danielporto** [comment]
Sure, thanks.
