### ISSUE TITLE
flutter pub get failed

### ISSUE THREAD

**Issue by aqibaja** [fastogt/fastotvlite_mobile#7]
how i can solve this problem ? when i run "flutter pub get" :
Because every version of flutter_localizations from sdk depends on intl 0.16.0 and every version of flutter_fastotv_common from git depends on intl ^0.16.1, flutter_localizations from sdk is incompatible with flutter_fastotv_common from git.
So, because fastotvlite depends on both flutter_fastotv_common from git and flutter_localizations any from sdk, version solving failed.

**Comment by topilski** [comment]
Hello, can you please try to execute `flutter pub upgrade` and also please use last sources.

**Comment by topilski** [comment]
ping

**Comment by aqibaja** [comment]
thanks, sorry late commend
